'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AcompanharPaciente

    '''<summary>
    '''lblPaciente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaciente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lkbAvaliacaoClinica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbAvaliacaoClinica As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lkbProgressao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbProgressao As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lkbDietaPaciente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbDietaPaciente As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lkbConsultasRealizadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbConsultasRealizadas As Global.System.Web.UI.WebControls.LinkButton
End Class
