'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AvaliacaoClinica

    '''<summary>
    '''lkbAlimentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbAlimentos As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gdvAlimentosHabitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvAlimentosHabitos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ldsAlimentosHabitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldsAlimentosHabitos As Global.System.Web.UI.WebControls.LinqDataSource

    '''<summary>
    '''lkbAparehoGastrointestinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbAparehoGastrointestinal As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''gdvAparelhoGastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvAparelhoGastro As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ldsAparelhoGastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldsAparelhoGastro As Global.System.Web.UI.WebControls.LinqDataSource

    '''<summary>
    '''lkbConsultas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbConsultas As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gdvConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvConsulta As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ldsConsultas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldsConsultas As Global.System.Web.UI.WebControls.LinqDataSource

    '''<summary>
    '''lkbHistorico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbHistorico As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ldsHistoricoSaude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldsHistoricoSaude As Global.System.Web.UI.WebControls.LinqDataSource
End Class
