'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CadastroAparelhoGastrointestinal

    '''<summary>
    '''ddlDisfagia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDisfagia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDisfagiaAlimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisfagiaAlimento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDisfagiaTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisfagiaTipo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOdinofagia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOdinofagia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDispepsia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDispepsia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEpgastragia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEpgastragia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRegurgitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegurgitacao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPirose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPirose As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlNauseas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNauseas As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlVomitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVomitos As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txthoraVomitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthoraVomitos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCaracVomitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCaracVomitos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDorAbdominal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDorAbdominal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLocalDorAbdominal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocalDorAbdominal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCaracDorAbdominal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCaracDorAbdominal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRitmoIntestinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRitmoIntestinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAspectoFeses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAspectoFeses As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCorFeses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorFeses As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDensidadeFeses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDensidadeFeses As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDorFeses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDorFeses As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSangueFeses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSangueFeses As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtMedicamentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMedicamentos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button
End Class
