'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CadastroMedidasAntropometricas

    '''<summary>
    '''txPesoAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txPesoAtual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoDesejado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoDesejado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoHabitual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoHabitual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAltura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAltura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPressaoArterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPressaoArterial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTriceps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTriceps As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSubescapular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubescapular As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBiceps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBiceps As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCoxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoxa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSupraIliaca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupraIliaca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAbdomen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbdomen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPunho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPunho As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBraco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBraco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAbdominal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbdominal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCintura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCintura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQuadril control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuadril As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPercentualGordura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPercentualGordura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoMagro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoMagro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoGordo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoGordo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoMuscular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoMuscular As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalAgua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAgua As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button
End Class
